//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Model { get; set; }
        public string NumberPart { get; set; }
        public Nullable<int> PrintSpeed { get; set; }
        public Nullable<int> MaxMonthly { get; set; }
        public Nullable<int> RecMonthly { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> Pvp { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
